# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    client:
        enabled: false

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

server:
    port: 80
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
       
mq:
    queueManager: QMONS01
    host: des-ssmq-01
    port: 1414
    channel: SYSTEM.DEF.SVRCONN
    username: mqm
    password: 
    incomingQueue: 
    outgoingQueue:

wxs:
    catalogServerAddresses: des-sswas-01:9810
    objectGridName: Grid

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: d5f5bbd2b90398c45bc85f85640cd8ade07aefaa
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
