version: '2'
services:
    onssagerparametrizacao-mongodb:
        container_name: onssagerparametrizacao-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/ONSSagerParametrizacao/mongodb/:/data/db/
